### ISSUE TITLE
Architectural Diagram

### ISSUE THREAD

**Issue by VRagulina** [GSA-TTS/10x-nad-ch#24]
Document proposed Architectural Diagram for the new Hub

AC: Document reviewed and accepted by the team and DoT 
```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/10x-nad-ch/issues/72
```

**Comment by akuny** [comment]
First draft of an architecture diagram: https://github.com/GSA-TTS/10x-nad-ch/blob/main/documentation/architecture/architecture-diagram.png

Accompanying explanatory text: https://github.com/GSA-TTS/10x-nad-ch/blob/main/documentation/architecture/README.md

**Comment by VRagulina** [comment]
Need to update diagram to reflect login.gov and using generic .gov cloud services
